OID_BASE = ".1.3.6.1.4.1.53864"

OID_NOISE   = OID_BASE + ".1.1"
OID_BITS    = OID_BASE + ".1.2"
OID_ERRORS  = OID_BASE + ".1.3"
OID_BER     = OID_BASE + ".1.4"
OID_RESET_BER = OID_BASE + ".1.5"
OID_PACKET_RATE = OID_BASE + ".1.6"
OID_FREQ_OFFSET = OID_BASE + ".1.7"
OID_MOD_SCHEME = OID_BASE + ".1.8"
OID_SNR = OID_BASE + ".1.9"
OID_BER_INJECT = OID_BASE + ".1.10"


OIDS = [
    OID_NOISE,
	OID_BITS,
	OID_ERRORS,
	OID_BER,
	OID_RESET_BER,
	OID_PACKET_RATE,
	OID_FREQ_OFFSET,
	OID_MOD_SCHEME,
	OID_SNR,
	OID_BER_INJECT,
]