OID_BASE = ".1.3.6.1.4.1.53864"

OID_NOISE   = OID_BASE + ".1.1"
OID_BITS    = OID_BASE + ".1.2"
OID_ERRORS  = OID_BASE + ".1.3"
OID_BER     = OID_BASE + ".1.4"


OIDS = [OID_NOISE, OID_BITS, OID_ERRORS, OID_BER]