agentaddress 127.0.0.1

rocommunity public 127.0.0.1 .1
rwcommunity private 127.0.0.1

pass_persist .1.3.6.1.4.1.53864 /usr/bin/python3 -u /home/georgia/Desktop/SDR/snmp/phy_snmp.py
# extend phyBER /home/georgia/Desktop/SDR/snmp/phy_snmp.py ber
# extend phyBits   /home/georgia/Desktop/SDR/snmp/phy_snmp.py bits
# extend phyErrors /home/georgia/Desktop/SDR/snmp/phy_snmp.py errors
# extend phyNoise /home/georgia/Desktop/SDR/snmp/phy_snmp.py noise
