agentaddress 127.0.0.1

rocommunity public 127.0.0.1 .1

extend phyBER /home/georgia/Desktop/SDR/snmp/phy_snmp.py ber
extend phyBits   /home/georgia/Desktop/SDR/snmp/phy_snmp.py bits
extend phyErrors /home/georgia/Desktop/SDR/snmp/phy_snmp.py errors
